@baseUrl=http://localhost:3333

# sessionOperator se quiser testar como usuário operador
# sessionAdmin se quiser testar como usuário admin
@authToken={{sessionAdmin.response.body.token}}

# @name sessionOperator
POST {{baseUrl}}/auth/session
Content-Type: application/json

{
    "login": "yan-teste",
    "password": "123"
}

###

# @name sessionAdmin
POST {{baseUrl}}/auth/session
Content-Type: application/json

{
    "login": "admin-test",
    "password": "123"
}

###

# @name healthCheck
GET {{baseUrl}}/health

###

# @name me
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

###

# @name listUsers
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "login": "admin-teste",
    "name": "Administrator",
    "password": "123",
    "permission": "admin",
    "registration": "40028922",
    "role": "dev"
}

###

# @name updateUser
PATCH {{baseUrl}}/users/:id
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "yanzin",
    "permission": "admin"
}

### 

# @name createCategory
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Test Category"
}

###

# @name listCategoriesWithPagination
GET {{baseUrl}}/categories
Authorization: Bearer {{authToken}}

###

# @name listAllCategories
GET {{baseUrl}}/categories/all
Authorization: Bearer {{authToken}}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/:id
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Update Test Category"
}

###

# @name getBook
GET {{baseUrl}}/books/288a67d3-294d-4edc-97f2-76aa0859974e
Authorization: Bearer {{authToken}}

###

# @name createBook
POST {{baseUrl}}/books
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Test Book",
    "author": "Test Author",
    "release_year": 2023,
    "price": 99.99,
    "categoryIds": []
}

###

# @name listBooksWithPagination
GET {{baseUrl}}/books
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name listAllBooks
GET {{baseUrl}}/books/all?search=o
Authorization: Bearer {{authToken}}

###

# @name updateBook
PATCH {{baseUrl}}/books/2a205a2d-8db2-4acd-a62c-ab10a8a1347c
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Updated Title",
    "author": "Updated Author",
    "release_year": 2026,
    "price": 1000,
    "categoryIds": []
}

###

# @name createEstablishment
POST {{baseUrl}}/establishments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Estabelecimento Teste",
    "cnpj": "44.595.458/0001-06",
    "state": "Ceará",
    "city": "Aracati",
    "district": "Rua doida",
    "cep": "62800-000",
    "description": "Teste de criação de estabelecimento"
}

### 

# @name listEstablishmentsWithPagination
GET {{baseUrl}}/establishments
Authorization: Bearer {{authToken}}

###

# @name listAllEstablishments
GET {{baseUrl}}/establishments/all
Authorization: Bearer {{authToken}}

###

# @name updateEstablishment

PATCH {{baseUrl}}/establishments/7ceacc14-e28f-4e35-905e-6fa09cc58041
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Test Name"
}

###

# @name listStockItems

GET {{baseUrl}}/stocks?search=VNns7f
Authorization: Bearer {{authToken}}

### 

# @name createInventory

POST {{baseUrl}}/inventories
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "establishment_id": "d54fbeee-0ea2-4854-b2f0-0f4ae808445d",
    "total_quantity": 20,
    "inventoryBooks": [
        {
            "book_id": "2715076c-2077-4b64-99a5-fc6c9ce4584e",
            "quantity": 10
        },
        {
            "book_id": "1420a8ff-bad9-43f2-a34e-55d2b5810cf0",
            "quantity": 10
        }
    ]
}


###

# @name listInventories

GET {{baseUrl}}/inventories
Authorization: Bearer {{authToken}}

###

# @name getInventory
GET {{baseUrl}}/inventories/53672b90-291b-49a0-8bcd-8044aba486f7
Authorization: Bearer {{authToken}}

###

# @name processInventory
POST {{baseUrl}}/inventories/process/53672b90-291b-49a0-8bcd-8044aba486f7
Authorization: Bearer {{authToken}}

###

# @name getInventoryBooks
GET {{baseUrl}}/inventories/082f0c32-f088-42c3-8bc8-f37a9ebba9f0/books
Authorization: Bearer {{authToken}}
