@baseUrl=http://localhost:3333

# troque para sessionOperator se quiser testar como usuário operador
@authToken={{sessionAdmin.response.body.token}}

# @name healthCheck
GET {{baseUrl}}/health

###

# @name me
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

###

# @name listUsers
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "login": "admin-teste",
    "name": "Administrator",
    "password": "123",
    "permission": "admin",
    "registration": "40028922",
    "role": "dev"
}

###

# @name sessionOperator
POST {{baseUrl}}/auth/session
Content-Type: application/json

{
    "login": "yan-teste",
    "password": "123"
}

###

# @name sessionAdmin
POST {{baseUrl}}/auth/session
Content-Type: application/json

{
    "login": "admin-teste",
    "password": "123"
}