services:
  database:
    image: postgres
    container_name: booktu-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=booktu
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    build: .
    container_name: booktu-api
    ports:
      - 3333:3333
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - database
      - redis

volumes:
  pgdata:
    driver: local
