export const booksTitles = [
  "O Segredo da Última Aurora",
  "Além das Estrelas",
  "Códigos do Silêncio",
  "A Filha do Vento",
  "Fragmentos do Infinito",
  "O Jardim das Sombras",
  "A Cidade Submersa",
  "No Coração da Tempestade",
  "O Herdeiro do Tempo",
  "Canções para um Mundo Perdido",
  "A Farsa dos Imortais",
  "Sob a Luz do Eclipse",
  "Ecos da Mente",
  "Os Guardiões do Véu",
  "Crônicas de um Sonhador",
  "Marés da Memória",
  "A Última Fortaleza",
  "A Teia do Destino",
  "Sombras do Paraíso",
  "Diário de um Viajante Eterno",
  "O Labirinto de Cristal",
  "Vozes na Neblina",
  "O Alvorecer dos Deuses",
  "Entre Dois Mundos",
  "O Olhar da Serpente",
  "Caminhos Esquecidos",
  "O Último Portal",
  "Sussurros da Terra",
  "Asas de Cinza",
  "A Torre dos Segredos",
  "Ventos do Norte",
  "A Maldição do Oráculo",
  "O Enigma do Abismo",
  "Tempestade de Luz",
  "Fragmentos do Amanhã",
  "As Crônicas da Lua Azul",
  "O Despertar da Rosa Negra",
  "A Guardiã do Labirinto",
  "O Livro das Marés",
  "Ecos do Subsolo",
  "Estações da Alma",
  "O Último Feiticeiro",
  "A Ilha Sem Nome",
  "Entre Chamas e Gelo",
  "A Herança Esquecida",
  "A Mente por Trás do Espelho",
  "Segredos em Vermelho",
  "A Promessa de Areia",
  "O Grito das Estrelas",
  "A Lenda do Lobo de Prata",
];
