export const categoriesNames = [
  "Ficção Científica",
  "Fantasia",
  "Romance",
  "Terror",
  "Suspense",
  "Mistério",
  "Aventura",
  "Drama",
  "Comédia",
  "Biografia",
  "História",
  "Autoajuda",
  "Negócios",
  "Desenvolvimento Pessoal",
  "Tecnologia",
  "Filosofia",
  "Poesia",
  "Literatura Clássica",
  "Juvenil",
  "Infantil",
];
